# Generated by Django 3.1.5 on 2021-02-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchResult',
            new_name='MatchResults',
        ),
    ]
