# Generated by Django 3.1.5 on 2021-02-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_matches', '0003_auto_20210208_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresults',
            name='match_details',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
