# Generated by Django 3.1.5 on 2021-02-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_matches', '0004_auto_20210208_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresults',
            name='match_details',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
