# Generated by Django 3.1.5 on 2021-02-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_matches', '0005_auto_20210208_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresults',
            name='type_sport',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
