# Generated by Django 3.1.5 on 2021-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_matches', '0007_matchresults_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresults',
            name='match_details',
            field=models.JSONField(blank=True, max_length=1000, null=True),
        ),
    ]
