# Generated by Django 3.1.5 on 2021-02-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_matches', '0008_auto_20210215_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresults',
            name='date_match',
            field=models.DateField(blank=True, null=True),
        ),
    ]
