# Generated by Django 3.1.5 on 2021-02-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_matches', '0009_auto_20210215_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresults',
            name='date_match',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
