# Generated by Django 3.1.5 on 2021-02-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_matches', '0011_auto_20210215_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsWinAllTeamNBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one', models.CharField(max_length=350, null=True)),
                ('team_two', models.CharField(max_length=350, null=True)),
                ('win_team_one', models.IntegerField(default=0)),
                ('win_team_two', models.IntegerField(default=0)),
                ('win_percent_team_one', models.FloatField(default=0)),
                ('win_percent_team_two', models.FloatField(default=0)),
                ('win_team_one_guest', models.IntegerField(default=0)),
                ('win_team_one_home', models.IntegerField(default=0)),
                ('win_team_two_guest', models.IntegerField(default=0)),
                ('win_team_two_home', models.IntegerField(default=0)),
            ],
        ),
    ]
