# Generated by Django 3.1.5 on 2021-04-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_matches', '0012_statswinallteamnba'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsNBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=350)),
            ],
        ),
    ]
